### ISSUE TITLE
Eliminar operador de atributo invisible en vista

### ISSUE THREAD

**Issue by ghost** [bmya/account-financial-tools#8]
Hola @Danisan ,

He visto que el operador '|' es incorrecto, se debería de eliminar.

https://github.com/bmya/account-financial-tools/blob/3fccb47b5084e9cb7c8517a99a35094f7fbc56d6/account_document/view/account_invoice_view.xml#L66-L68

Un saludo!

**Comment by Danisan** [comment]
Se resuelve en la rama 11.0_new y lo consideramos resuelto, puesto que es esa la rama que estamos usando en l10n-chile-11

**Comment by ghost** [comment]
Hola @Danisan ,

Por tu comentario entiendo que en producción tenéis la rama 11.0_new, debería de dejar de sincronizar nuestra rama con 11.0_dev y pasar a 11.0_new?

Gracias!
